<?php

/**
 * Implements hook_theme().
 */
function azure_textfield_theme($existing, $type, $theme, $path): array {
  return [
    'azure_textfield' => [
      'render element' => 'element',
    ],
    'relux' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function azure_textfield_theme_suggestions_relux(array $variables) {
  $suggestions = [];
  $suggestions[] = 'relux__textfield__input';
  return $suggestions;
}