<?php

use Drupal\Component\Serialization\Yaml;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function azure_content_theme_suggestions_block_alter(array &$suggestions, array $variables): void {
  if ($variables['elements']['#plugin_id'] === 'system_main_block') {
    //    $suggestions[] = 'block__system_azure_main_content';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function azure_content_theme_registry_alter(&$theme_registry) {
  $theme_registry['block__system_azure_main_content'] = $theme_registry['block'];
  $theme_registry['block__system_azure_main_content']['path'] = \Drupal::service('extension.list.module')
      ->getPath('azure_content') . '/templates/';
  $theme_registry['block__system_azure_main_content']['template'] = str_replace('_', '-', 'block__system_azure_main_content');
}

/**
 * Implements hook_theme().
 */
function azure_content_theme($existing, $type, $theme, $path): array {
  return [
    'azure_content' => [
      'render element' => 'content',
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function azure_content_library_info_alter(&$libraries, $extension) {
  if (isset($libraries['azure_content.main'])) {
    $libraries['azure_content.main']['js']['js/extend-example.js'] = [];
  }
}