<?php

use Drupal\Component\Serialization\Yaml;
use Drupal\Component\Utility\Xss;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function azure_content_theme_suggestions_block_alter(array &$suggestions, array $variables): void {
  if ($variables['elements']['#plugin_id'] === 'system_main_block') {
    //    $suggestions[] = 'block__system_azure_main_content';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function azure_content_theme_registry_alter(&$theme_registry) {
  $theme_registry['block__system_azure_main_content'] = $theme_registry['block'];
  $theme_registry['block__system_azure_main_content']['path'] = \Drupal::service('extension.list.module')
      ->getPath('azure_content') . '/templates/';
  $theme_registry['block__system_azure_main_content']['template'] = str_replace('_', '-', 'block__system_azure_main_content');
}

/**
 * Implements hook_theme().
 */
function azure_content_theme($existing, $type, $theme, $path): array {
  return [
    'azure_content' => [
      'render element' => 'content',
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function azure_content_library_info_alter(&$libraries, $extension) {
  if (isset($libraries['azure_content.main'])) {
    $libraries['azure_content.main']['js']['/libraries/js/extend-example.js'] = [];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function azure_content_preprocess_azure_content(&$variables) {
  $variables['xss_attack'] = FALSE;
    $variables['attributes']['class'][] = 'azure-preprocess-class';

}

/**
 * Implements hook_preprocess().
 */
function azure_content_preprocess(&$variables, $hook) {
  if ($hook === 'region' && $variables['region'] === 'content') {
    $var = TRUE;
  }
  if (isset($variables['elements']['#theme']) && $variables['elements']['#theme'] === 'block') {
    if ($variables['elements']['#id'] === 'olivero_content' &&
      $variables['elements']['#plugin_id'] === 'system_main_block') {
//      $variables['content']['new'] = [
//        '#markup' => 'hell1o',
//      ];
    }
    $check = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function azure_content_preprocess_html(&$variables) {
  // example how to add class inside body tag html
  $variables['attributes']['class'][] = 'example-class-inside-body';
}
